//! dwl backend for the [`WindowManager`] seam.
//!
//! Speaks `dwl-ipc-unstable-v2` (the same protocol waybar-dwl uses) on a **second, dedicated
//! `wayland-client` connection** — not GDK's (see `docs/ARCHITECTURE.md`: objects can't cross
//! connections, and sharing GDK's fd would race GTK's dispatch). The host integrates
//! [`DwlBackend::fd`] into the GLib main loop and calls [`DwlBackend::dispatch`] on wake-ups.
//!
//! Bindings are generated by `wayland-scanner` from the vendored XML — never hand-rolled.

use std::os::fd::{AsFd, AsRawFd, RawFd};

use anyhow::{bail, Result};
use tracing::debug;
use wafflebar_core::{Tag, TagState, WindowManager, WmCommand, WmEvent};
use wayland_client::protocol::wl_output::{self, WlOutput};
use wayland_client::protocol::wl_registry::{self, WlRegistry};
use wayland_client::protocol::wl_seat::{self, WlSeat};
use wayland_client::{Connection, Dispatch, EventQueue, QueueHandle};

/// `wayland-scanner`-generated client bindings for dwl-ipc-unstable-v2.
#[allow(non_snake_case, clippy::all)]
mod proto {
    use wayland_client;
    use wayland_client::protocol::*;
    pub mod __interfaces {
        use wayland_client::backend as wayland_backend;
        use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocols/dwl-ipc-unstable-v2.xml");
    }
    use self::__interfaces::*;
    wayland_scanner::generate_client_code!("protocols/dwl-ipc-unstable-v2.xml");
}
use proto::zdwl_ipc_manager_v2::{self, ZdwlIpcManagerV2};
use proto::zdwl_ipc_output_v2::{self, ZdwlIpcOutputV2};

/// Per-output state. // Output lifetime: keyed by the `WlOutput` proxy (via `oid`); when the
/// output goes away we drop this entry and its `ZdwlIpcOutputV2` so stale handles never pile up.
struct OutputState {
    oid: u32,
    wl_output: WlOutput,
    ipc: Option<ZdwlIpcOutputV2>,
    name: String,
    x: i32,
    // committed (last full frame) — used by snapshot()
    tags: Vec<Tag>,
    symbol: String,
    title: String,
    appid: String,
    // per-frame accumulators (reset on `frame`)
    acc_tags: Vec<Tag>,
    acc_symbol: String,
    acc_title: String,
    acc_appid: String,
}

#[derive(Default)]
struct State {
    manager: Option<ZdwlIpcManagerV2>,
    /// Bound + cached now though unused until PR2 (foreign-toplevel `activate` needs a seat).
    seat: Option<WlSeat>,
    next_oid: u32,
    outputs: Vec<OutputState>,
    pending: Vec<WmEvent>,
}

impl State {
    fn output_by_oid(&mut self, oid: u32) -> Option<&mut OutputState> {
        self.outputs.iter_mut().find(|o| o.oid == oid)
    }
    /// Bind a dwl ipc_output for `oid` if the manager is up and it isn't bound yet.
    fn ensure_ipc(&mut self, oid: u32, qh: &QueueHandle<Self>) {
        let Some(mgr) = self.manager.clone() else { return };
        if let Some(o) = self.outputs.iter_mut().find(|o| o.oid == oid) {
            if o.ipc.is_none() {
                o.ipc = Some(mgr.get_output(&o.wl_output, qh, oid));
            }
        }
    }
}

/// The dwl backend: owns its Wayland connection, queue, and accumulated state.
pub struct DwlBackend {
    conn: Connection,
    queue: EventQueue<State>,
    state: State,
}

impl DwlBackend {
    /// Connect, bind globals, and pull the initial state. Errors if the compositor doesn't
    /// implement dwl-ipc (so the host can fall back gracefully on non-dwl sessions).
    pub fn connect() -> Result<Self> {
        let conn = Connection::connect_to_env()?;
        let mut queue = conn.new_event_queue();
        let qh = queue.handle();
        conn.display().get_registry(&qh, ());
        let mut state = State::default();
        // 1st roundtrip: registry globals (manager/outputs/seat). 2nd: get_output replies +
        // the first status frame for each output.
        queue.roundtrip(&mut state)?;
        queue.roundtrip(&mut state)?;
        if state.manager.is_none() {
            bail!("compositor does not implement zdwl_ipc_manager_v2 (not dwl, or unpatched)");
        }
        debug!(outputs = state.outputs.len(), "dwl backend connected");
        Ok(Self { conn, queue, state })
    }

    /// Raw fd for GLib `unix_fd_add_local`.
    pub fn fd(&self) -> RawFd {
        self.conn.as_fd().as_raw_fd()
    }

    /// Drive the queue once (call on an fd wake-up) and return the events that accumulated.
    ///
    /// wayland-client read-guard dance (do not "simplify"): `prepare_read` returns `None` when
    /// events are already queued — then we just `dispatch_pending`. When it returns a guard, the
    /// fd has been signalled readable by GLib, so `read()` won't block; then `dispatch_pending`.
    /// We also `flush()` first so our outgoing requests are on the wire.
    pub fn dispatch(&mut self) -> Vec<WmEvent> {
        let _ = self.conn.flush();
        if let Some(guard) = self.conn.prepare_read() {
            let _ = guard.read(); // non-blocking: GLib told us the fd is readable
        }
        let _ = self.queue.dispatch_pending(&mut self.state);
        std::mem::take(&mut self.state.pending)
    }
}

impl WindowManager for DwlBackend {
    fn snapshot(&self) -> Vec<WmEvent> {
        let mut out = Vec::new();
        for o in &self.state.outputs {
            out.push(WmEvent::Tags {
                output: o.name.clone(),
                tags: o.tags.clone(),
            });
            out.push(WmEvent::Layout {
                output: o.name.clone(),
                symbol: o.symbol.clone(),
            });
            out.push(WmEvent::ActiveWindow {
                output: o.name.clone(),
                title: o.title.clone(),
                app_id: o.appid.clone(),
            });
        }
        out
    }

    fn execute(&mut self, cmd: &WmCommand) {
        match cmd {
            WmCommand::FocusTag { output, tag } => {
                if let Some(o) = self.state.outputs.iter().find(|o| &o.name == output) {
                    if let Some(ipc) = &o.ipc {
                        ipc.set_tags(1 << tag, 1);
                    }
                }
            }
            WmCommand::SetLayout { output, index } => {
                if let Some(o) = self.state.outputs.iter().find(|o| &o.name == output) {
                    if let Some(ipc) = &o.ipc {
                        ipc.set_layout(*index);
                    }
                }
            }
            // window commands (activate/close/minimize) arrive with foreign-toplevel in PR2.
            _ => {}
        }
        // Flush after every command — GLib's fd integration won't flush our requests for us.
        let _ = self.conn.flush();
    }
}

// ---- Dispatch impls ----

impl Dispatch<WlRegistry, ()> for State {
    fn event(
        state: &mut Self,
        registry: &WlRegistry,
        event: wl_registry::Event,
        _: &(),
        _conn: &Connection,
        qh: &QueueHandle<Self>,
    ) {
        let wl_registry::Event::Global {
            name,
            interface,
            version,
        } = event
        else {
            return;
        };
        match interface.as_str() {
            "zdwl_ipc_manager_v2" => {
                let mgr =
                    registry.bind::<ZdwlIpcManagerV2, _, _>(name, version.min(2), qh, ());
                state.manager = Some(mgr);
                // Bind ipc_outputs for any outputs that arrived before the manager.
                let oids: Vec<u32> = state.outputs.iter().map(|o| o.oid).collect();
                for oid in oids {
                    state.ensure_ipc(oid, qh);
                }
            }
            "wl_output" => {
                let oid = state.next_oid;
                state.next_oid += 1;
                let wl_output =
                    registry.bind::<WlOutput, _, _>(name, version.min(4), qh, oid);
                state.outputs.push(OutputState {
                    oid,
                    wl_output,
                    ipc: None,
                    name: String::new(),
                    x: 0,
                    tags: Vec::new(),
                    symbol: String::new(),
                    title: String::new(),
                    appid: String::new(),
                    acc_tags: Vec::new(),
                    acc_symbol: String::new(),
                    acc_title: String::new(),
                    acc_appid: String::new(),
                });
                state.ensure_ipc(oid, qh);
            }
            "wl_seat" => {
                state.seat = Some(registry.bind::<WlSeat, _, _>(name, version.min(7), qh, ()));
            }
            _ => {}
        }
    }
}

impl Dispatch<WlOutput, u32> for State {
    fn event(
        state: &mut Self,
        _: &WlOutput,
        event: wl_output::Event,
        oid: &u32,
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
        let Some(o) = state.output_by_oid(*oid) else { return };
        match event {
            wl_output::Event::Name { name } => o.name = name,
            wl_output::Event::Geometry { x, .. } => o.x = x,
            _ => {}
        }
    }
}

impl Dispatch<WlSeat, ()> for State {
    fn event(_: &mut Self, _: &WlSeat, _: wl_seat::Event, _: &(), _: &Connection, _: &QueueHandle<Self>) {}
}

impl Dispatch<ZdwlIpcManagerV2, ()> for State {
    fn event(
        _: &mut Self,
        _: &ZdwlIpcManagerV2,
        _: zdwl_ipc_manager_v2::Event,
        _: &(),
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
        // manager `tags`/`layout` events advertise capabilities; not needed for v1 rendering.
    }
}

impl Dispatch<ZdwlIpcOutputV2, u32> for State {
    fn event(
        state: &mut Self,
        _: &ZdwlIpcOutputV2,
        event: zdwl_ipc_output_v2::Event,
        oid: &u32,
        _: &Connection,
        _: &QueueHandle<Self>,
    ) {
        use zdwl_ipc_output_v2::Event;
        let Some(o) = state.output_by_oid(*oid) else { return };
        match event {
            Event::Tag {
                tag,
                state: tstate,
                clients,
                focused,
            } => {
                let ts = match tstate.into_result().unwrap_or(zdwl_ipc_output_v2::TagState::None) {
                    zdwl_ipc_output_v2::TagState::Active => TagState::Active,
                    zdwl_ipc_output_v2::TagState::Urgent => TagState::Urgent,
                    _ => TagState::None,
                };
                o.acc_tags.push(Tag {
                    index: tag,
                    name: (tag + 1).to_string(),
                    state: ts,
                    focused: focused != 0,
                    occupied: clients > 0,
                });
            }
            Event::LayoutSymbol { layout } => o.acc_symbol = layout,
            Event::Title { title } => o.acc_title = title,
            Event::Appid { appid } => o.acc_appid = appid,
            Event::Frame => {
                // Commit the accumulated full snapshot and emit WmEvents.
                o.tags = std::mem::take(&mut o.acc_tags);
                o.symbol = std::mem::take(&mut o.acc_symbol);
                o.title = std::mem::take(&mut o.acc_title);
                o.appid = std::mem::take(&mut o.acc_appid);
                let (name, tags, symbol, title, appid) = (
                    o.name.clone(),
                    o.tags.clone(),
                    o.symbol.clone(),
                    o.title.clone(),
                    o.appid.clone(),
                );
                state.pending.push(WmEvent::Tags { output: name.clone(), tags });
                state.pending.push(WmEvent::Layout { output: name.clone(), symbol });
                state.pending.push(WmEvent::ActiveWindow {
                    output: name,
                    title,
                    app_id: appid,
                });
            }
            _ => {} // active/fullscreen/floating/layout(index)/toggle_visibility: not needed for v1
        }
    }
}
